// Reads .env and writes config.js — run this any time you change .env.
// Usage:  node build-config.js
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  console.error('No .env file found. Copy .env.example to .env and fill in your Firebase values first.');
  process.exit(1);
}

const env = {};
fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) return;
  const idx = trimmed.indexOf('=');
  if (idx === -1) return;
  env[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
});

const required = [
  'FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID'
];
const missing = required.filter(k => !env[k] || env[k].startsWith('YOUR_'));
if (missing.length) {
  console.warn('Warning: these look like placeholders still — fill them in .env:', missing.join(', '));
}

const output = `// AUTO-GENERATED by build-config.js — do not edit by hand, and do not commit this file.
window.FIREBASE_CONFIG = {
  apiKey: "${env.FIREBASE_API_KEY || ''}",
  authDomain: "${env.FIREBASE_AUTH_DOMAIN || ''}",
  projectId: "${env.FIREBASE_PROJECT_ID || ''}",
  storageBucket: "${env.FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${env.FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId: "${env.FIREBASE_APP_ID || ''}"
};
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), output);
console.log('config.js generated from .env ✔');
