// AUTO-GENERATED by build-config.js — do not edit by hand, and do not commit this file.
window.FIREBASE_CONFIG = {
  apiKey: "AIzaSyBTwuBzx_fzSB8sKf6xUBdxUB2br7lzl_Y",
  authDomain: "exhibition-a2997.firebaseapp.com",
  projectId: "exhibition-a2997",
  storageBucket: "exhibition-a2997.firebasestorage.app",
  messagingSenderId: "844792744576",
  appId: "1:844792744576:web:a0899f0dade7aad72ab465"
};
